Playbook5/Source/web/Areas/Management/Models/Reporting/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class ApplicationUser
    {
        public string Id { get; set; }
        public string TeamId { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public bool isOwner { get; set; }
        public string Position { get; set; }

        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
        
    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/PlayReports.cs
namespace web.Areas.Management.Models.Reporting
{
    public class PlayReports
    {
        public string PlayName { get; set; }
        public string Position { get; set; }
        public string KeyIndicator { get; set; }
        public string Reps { get; set; }

    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/SnapShotReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class SnapShotReport
    {
        public string MostViewedPlay { get; set; }
        public string MostViewFromPosition { get; set; }
        public string LeastViewFromPosition { get; set; }
        public string OverallPercentage { get; set; }
        public string AmountOfPlaysWithoutKeyIndicator { get; set; }
        public string LeastViewedPlay { get; set; }
        public string TotalReps { get; set; }
        public string TotalIncorrect { get; set; }
        public string TotalCorrect { get; set; }
    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/TeamReports.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class TeamReports
    {
        public TeamReports()
        {
            UserList = new List<UserReports>();
        }
        public string TeamName { get; set; }
        public List<UserReports> UserList { get; set; }
    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/Teams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class Teams
    {
        public string Id { get; set; }
        public string AccessCode { get; set; }
        public string Name { get; set; }
        public string Field { get; set; }
        public string AccountOwner { get; set; }
        public string AccountPackage { get; set; }
        public DateTime AccountStartDate { get; set; }
        public string AccountManager { get; set; }
        public string LeagueDivConf { get; set; }
        public string Address { get; set; }
        public string StateOrProvince { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Language { get; set; }
        public string RosterCount { get; set; }
        public string TotalCustomPlays { get; set; }
        public string SecurityStatus { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ZipCode { get; set; }
        public string PaymentStatus { get; set; }
        public string AccountStatus { get; set; }
        public string Notes { get; set; }
        public string ArchievedPackages { get; set; }
        public string SecurityTickets { get; set; }
        public string SupportTickets { get; set; }

    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/UserData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class UserData
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string PlayId { get; set; }
        public string Position { get; set; }
        public string Reps { get; set; }
        public string Key { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/UserHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class UserHistory
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public DateTime Timestamp { get; set; }
        public string Action { get; set; }
        public string Postitions { get; set; }
        public string Reps { get; set; }
        public string Key { get; set; }

    }
}

Playbook5/Source/web/Areas/Management/Models/Reporting/UserReports.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace web.Areas.Management.Models.Reporting
{
    public class UserReports
    {
        public UserReports()
        {
            PlayList = new List<PlayReports>();
            SnapShot = new SnapShotReport();
        }
        public string PlayerName { get; set; }
        public List<PlayReports> PlayList { get; set; }
        public SnapShotReport SnapShot { get; set; }
    }
}

Playbook5/Source/web/Areas/Management/Models/TeamManagement/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using web.Models;

namespace web.Areas.Management.Models.TeamManagement
{
    public class Team
    {
        public Team()
        {
            TeamUsers = new List<TeamUser>();
            Plays = new List<Play>();
            Playbooks = new List<PlayBook>();
            TeamInstall = new TeamInstall();
        }

        public string Id { get; set; }

        [Display(Name = "Access Code")]
        [Required]
        public string AccessCode { get; set; }

        [Display(Name = "Team Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Field Size")]
        [Required]
        public string Field { get; set; }

        [Display(Name = "Account Representative")]
        [Required]
        public string AccountOwner { get; set; }

        [Display(Name = "Subscription Package")]
        [Required]
        public string AccountPackage { get; set; }

        [Display(Name = "Subscription Date")]
        public DateTime? AccountStartDate { get; set; }
        [Display(Name = "Representative")]
        [Required]
        public string AccountManager { get; set; }

        [Display(Name = "League/division/conference")]
        [Required]
        public string LeagueDivConf { get; set; }

        [Display(Name = "Street Address")]
        [Required]
        public string Address { get; set; }

        [Display(Name = "State")]
        [Required]
        public string StateOrProvince { get; set; }

        [Display(Name = "City")]
        [Required]
        public string City { get; set; }

        [Required]
        public string CountryId { get; set; }
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Display(Name = "Language")]
        [Required]
        public LanguageEnum Language { get; set; }

        [Display(Name = "Roster")]
        public int? RosterCount { get; set; }

        [Display(Name = "Total Pays")]
        public int? TotalCustomPlays { get; set; }

        public string SecurityStatus { get; set; }

        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Phone")]
        [Required]
        public string Phone { get; set; }

        [Display(Name = "Zip Code")]
        [Required]
        public string ZipCode { get; set; }

        [Display(Name = "Payment Status")]
        [Required]
        public PaymentStatusEnum PaymentStatus { get; set; }

        [Display(Name = "Account Status")]
        [Required]
        public AccountStatusEnum AccountStatus { get; set; }

        public string Notes { get; set; }

        [Display(Name = "Archived Packages")]
        public string ArchivedPackages { get; set; }

        [Display(Name = "Security Tickets")]
        public string SecurityTickets { get; set; }

        [Display(Name = "Support Tickets")]
        public string SupportTickets { get; set; }

        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        
        public List<TeamUser> TeamUsers { get; set; }
        public List<PlayBook> Playbooks { get; set; }
        public List<Play> Plays { get; set; }
        public TeamInstall TeamInstall { get; set; }


        //string teamId;
        //string name;
        //DateTime createDate;
        //DateTime expirationDate;
        //User[] users;
        //PlayBook[] playbooks;
    }
}

Playbook5/Source/web/Areas/Management/ViewModels/ReportingViewModel.cs
using RestSharp;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using web.Areas.Management.Models.Reporting;

namespace web.Areas.Management.ViewModels
{
    public class ReportingViewModel
    {
        public const string BASEURL = "http://playbook5servicev2.azurewebsites.net/";
        public ReportingViewModel()
        {
            ReportingModel = new TeamReports();
        }
        public TeamReports ReportingModel { get; set; }
        public List<Teams> TeamList { get; set; }
        public IEnumerable<SelectListItem> TeamSelectList { get; set; }
        public string TeamId { get; set; }
        public async Task<TeamReports> GetTeamReporting(string teamId)
        {
            var client = new RestClient();
            client.BaseUrl = new System.Uri(BASEURL);
            var request = new RestRequest("api/Reporting/TeamByIdReporting?Id=" + teamId, Method.GET);

            IRestResponse<TeamReports> response = client.Execute<TeamReports>(request);
            if (response.Data != null)
            {
                ReportingModel = response.Data;
            }
            return ReportingModel;
        }
        public void Load()
        {
            TeamSelectList = GetTeams().Select(c => new SelectListItem { Value = c.Id , Text = c.Name });
        }
        public List<Teams> GetTeams()
        {
            var client = new RestClient();
            client.BaseUrl = new System.Uri(BASEURL);
            var request = new RestRequest("api/Reporting/GetAllTeamsForReporting", Method.GET);

            IRestResponse <List<Teams>> response = client.Execute<List<Teams>>(request);
            if (response.Data != null)
            {
                TeamList = response.Data.ToList();
            }

            return TeamList;
        }
    }
}

Playbook5/Source/web/Areas/Management/ViewModels/TeamViewModel.cs
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using web.ApiInfrastructure.Client;
using web.Areas.Management.Models;
using web.Areas.Management.Models.TeamManagement;
using web.Models;

namespace web.Areas.Management.ViewModels
{
    public class TeamViewModel
    {
        public TeamViewModel()
        {
            TeamModel = new List<Team>();
            Team = new Team();
            CountrySelectList = new List<SelectListItem>();
        }

        public List<Team> TeamModel { get; set; }
        public Team Team { get; set; }
        public IEnumerable<SelectListItem> CountrySelectList { get; set; }


        public async Task<List<Team>> GetTeams()
        {
            TeamModel = await new RestHelper().Get<List<Team>>("api/TeamManagement/GetAllTeams");
            return TeamModel;
        }


        public async Task Load(string teamId = "")
        {
            if (string.IsNullOrEmpty(teamId))
            {
                await GetTeams();
            }
            else
            {
                var allCountries = await GetAllCountry();
                CountrySelectList = allCountries.Select(c => new SelectListItem { Value = c.Id, Text = c.Name }).ToList();
                await GetTeam(teamId);
                var country = allCountries.FirstOrDefault(x => string.Equals(x.Name, Team.Country, StringComparison.OrdinalIgnoreCase));
                Team.CountryId = country.Id;
                Team.TeamUsers = await GetUsersByTeamId(teamId);
                Team.Plays = await GetAllPlaysByTeamId(teamId);
                Team.Playbooks = await GetAllPlaybooksByTeamId(teamId);
                Team.TeamInstall = await GetAllTeamInstalledByTeamId(teamId);
            }
        }

        public async Task<List<Country>> GetAllCountry()
        {
            return await new RestHelper().Get<List<Country>>($"api//TeamManagement/GetAllCountries");
        }

        public async Task<Team> GetTeam(string teamId)
        {
            Team = await new RestHelper().Get<Team>($"api/TeamManagement/GetTeam?Id={teamId}");
            return Team;
        }

        public async Task<List<TeamUser>> GetUsersByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<TeamUser>>($"api/TeamManagement/GetAllUsersByTeamId?teamid={teamId}");
        }

        public async Task<List<Play>> GetAllPlaysByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<Play>>($"api/PlaybookManagement/GetAllPlaysByTeamId?teamid={teamId}");
        }

        public async Task<List<PlayBook>> GetAllPlaybooksByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<PlayBook>>($"api/PlaybookManagement/GetAllPlaybooksByTeamId?teamid={teamId}");
        }

        public async Task<TeamInstall> GetAllTeamInstalledByTeamId(string teamId)
        {
            return await new RestHelper().Get<TeamInstall>($"api/TeamManagement/TeamInstallsByIdGet/{teamId}");
        }

        public async Task<Team> CreateUpdateTeam()
        {
            return await new RestHelper().Post<Team>($"api/TeamManagement/CreateTeam", Team);
        }

        public async Task<PlayBook> CreateUpdateTeamPlayBook(PlayBook newPlayBook)
        {
            return await new RestHelper().Post<PlayBook>($"api/PlaybookManagement/CreatePlaybook", newPlayBook);
        }

        public async Task<bool> CreateUpdateTestInstall(TeamInstallDTO teamInstall)
        {
            return await new RestHelper().Post("api/TeamManagement/CreateTeamInstall", teamInstall);
        }

        public async Task<bool> InsertInstallPlay(string teamId, string playId)
        {
            return await new RestHelper().Get($"api/TeamManagement/InsertInstallPlay?id={teamId}&playId={playId}");
        }

        public async Task<bool> DeletePlayById(string id)
        {
            return await new RestHelper().Get($"api/PlaybookManagement/DeletePlayById?id={id}");
        }
        public async Task<bool> DeleteInstallPlay(string id, string playId)
        {
            return await new RestHelper().Get($"api/TeamManagement/DeleteInstallPlay?id={id}&playId={playId}");
        }

        public async Task<bool> SendInstallNotification(EmailDTO email)
        {
            return await new RestHelper().Post("email", email);
        }


        public async Task<bool> SavePlay(Play play)
        {
            return await new RestHelper().Post($"api/PlaybookManagement/CreatePlay", play);
        }

        public async Task<string> UploadPreview(string teamName, string playId, string fileName, byte[] fileBytes, int contentLength, string parameterName, string contentType)
        {
            return await new RestHelper().Upload($"api/PlaybookManagement/UploadPreviewFiles?teamName={teamName}&playId={playId}", fileName, fileBytes, contentLength, parameterName, contentType);
        }

        public async Task<string> UploadFile(string teamName, string playId, string fileName, byte[] fileBytes, int contentLength, string parameterName, string contentType)
        {
            return await new RestHelper().Upload($"api/PlaybookManagement/UploadFiles?teamName={teamName}&playId={playId}", fileName, fileBytes, contentLength, parameterName, contentType);
        }
    }
}

Playbook5/Source/web/Areas/Management/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using web.Areas.Management.ViewModels;

namespace web.Areas.Management.Controllers
{
    public class ReportingController : Controller
    {
        // GET: Management/Reporting
        [HttpPost]
        public async Task<ActionResult> Team(ReportingViewModel vm)
        {
            ReportingViewModel model = new ReportingViewModel();
            model.TeamId = vm.TeamId;
            model.ReportingModel = await vm.GetTeamReporting(vm.TeamId);
            model.Load();
            return View(model);
        }
        public ActionResult Team()
        {
            ReportingViewModel model = new ReportingViewModel();
            model.Load();
            return View(model);
        }
    }
}

Playbook5/Source/web/Areas/Management/Views/Reporting/Team.cshtml
@model web.Areas.Management.ViewModels.ReportingViewModel

@{
    ViewBag.Title = "Team";
}
<link href="~/Content/css/print.css" media="print" rel="stylesheet" />
<div class="row">&nbsp;</div>

        <div class="main-section">
            <div class="container w-container">
                @using (Html.BeginForm("Team", "Reporting", FormMethod.Post))
                {
                    <div class="row">
                        <div class="w-col w-col-12">
                                <div class="form-group">
                                    <label class="texttitle">Select Team</label>
                                    @Html.DropDownListFor(m => m.TeamId, Model.TeamSelectList)
                                </div>
                        </div>
                    </div>
                    <div class="row">

                        <div class="w-col w-col-12">
                            <div class="w-col w-col-3">
                                <div class="form-group">
                                    <button type="submit">Submit</button>
                                    @if (Model.ReportingModel.TeamName != null)
                                    {
                                        <a href="~/Management/Print/TeamReport?id=@Model.TeamId" target="_blank" id="printButton">Print</a>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }

                @if (Model.ReportingModel.TeamName != null)
                {
                    <div class="div-block-info divblock_topheading">
                        <h4 class="containerheading">Team Reports</h4>
                    </div>

                    <table style="width:100%" class="table tbl-items" id="printTable">
                        <tr>
                            <td colspan="10" class="underlineborder"> </td>
                        </tr>

                        <tr class="div-block-info divblock_topheading">
                            <td><h4 class="containerheading">Players</h4></td>
                        </tr>
                            <tr class="datalinerborder">
                                <th class="texttitle" colspan="4">Player</th>
                            </tr>

                            @for(int i = 0; i < Model.ReportingModel.UserList.Count; i++)
                            {
                                <tr class="datalinerborder">
                                    <td class="textdescription" colspan="2">
                                        <strong>@Model.ReportingModel.UserList[i].PlayerName</strong>
                                    </td>
                                    <td class="textdescription" colspan="1">
                                        <a href="#" onclick="TogglePlayerSnapShot(@i)">View Snap Shot</a>
                                    </td>
                                    <td class="textdescription" colspan="1">
                                        <a href="#" onclick="TogglePlays(@i)">View Players Plays</a>
                                    </td>
                                </tr>
                                <tbody class="datalinerborder" style="display:none;" id='_playersnapshot@(i)'>
                                    <tr>
                                        <td colspan="4">
                                            <div class="row">
                                                <div class="w-col w-col-12">
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">Overall Percentage</div>
                                                        <div class="textdescription">@Model.ReportingModel.UserList[i].SnapShot.OverallPercentage</div>
                                                    </div>
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Most Viewed From Position
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.MostViewFromPosition
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Least Viewed From Position
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.LeastViewFromPosition
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Most Viewed Play
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.MostViewedPlay
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">&nbsp;</div>
                                            <div class="row">

                                                <div class="w-col w-col-12">
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Amount Of Plays Without Key Indicator
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.AmountOfPlaysWithoutKeyIndicator
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Least Viewed Play
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.LeastViewedPlay
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-3">
                                                        <div class="texttitle">
                                                            Total Reps
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.TotalReps
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-1">
                                                        <div class="texttitle">
                                                            Total Incorrect
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.TotalIncorrect
                                                        </div>
                                                    </div>
                                                    <div class="w-col w-col-1">
                                                        <div class="texttitle">
                                                            Total Correct
                                                        </div>
                                                        <div class="textdescription">
                                                            @Model.ReportingModel.UserList[i].SnapShot.TotalCorrect
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                                <tbody class="datalinerborder" style="display:none;" id='_playssnapshot@(i)'>
                                    <tr>
                                        <th class="texttitle">
                                            Play Name
                                        </th>
                                        <th class="texttitle">
                                            Position
                                        </th>
                                        <th class="texttitle">
                                            Key Indicator
                                        </th>
                                        <th class="texttitle">
                                            Reps
                                        </th>
                                    </tr>
                                    @foreach (var play in Model.ReportingModel.UserList[i].PlayList)
                                    {
                                    <tr>
                                        <td class="textdescription">
                                            @play.PlayName
                                        </td>
                                        <td class="textdescription">
                                            @play.Position
                                        </td>
                                        <td class="textdescription">
                                            @play.KeyIndicator
                                        </td>
                                        <td class="textdescription">
                                            @play.Reps
                                        </td>
                                    </tr>
                                    }
                                </tbody>

                            }

                        </table>
                }
                else
                {
                    <text>No Results</text>
                }
            </div>
        </div>

        <script>
            function TogglePlayerSnapShot(i) {
                $('#_playersnapshot' + i).toggle(500);
            }
            function TogglePlays(i) {
                $('#_playssnapshot' + i).toggle(500);
            }
        </script>