Playbook5/Source/web/Areas/Management/Models/TeamManagement/Play.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using web.Models;

namespace web.Areas.Management.Models.TeamManagement
{
    public class Play
    {
        public Play()
        {
            OffenseFormation = new OffenseInformation();
        }
        public string TeamId { get; set; }
        public string Phone { get; set; }
        [Required]
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string isOwner { get; set; }
        public string Position { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string Id { get; set; }
        public string UserName { get; set; }
        public string SecurityStamp { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public List<string> Roles { get; set; }
        public string PasswordHash { get; set; }
        public List<object> Logins { get; set; }
        public List<object> Claims { get; set; }
        [Required]
        public string Install { get; set; }
        public OffenseInformation OffenseFormation { get; set; }
        public DefenseFormation DefenseFormation { get; set; }
        [Required]
        public string IndicatorSet { get; set; }
        [Required]
        public string Personnel { get; set; }
        [Required]
        public string PlayType { get; set; }
        [Required]
        public string Hash { get; set; }
        public string PlaybookId { get; set; }
        public string TeamName { get; set; }
        public string PreviewUrl { get; set; }
        public string SvgUrl { get; set; }
        [Display(Name = "Recommended Plays")]
        public string RecommendedPlayList { get; set; }
        public List<RecommendedPlay> RecommendedPlays { get; set; }
        public bool Active { get; set; } = true;
    }

    public class OffenseInformation
    {
        public string Name { get; set; }
        public string FriendlyDisplay { get; set; }
    }

    public class RecommendedPlay
    {
        public string PlayId { get; set; }
    }

}

Playbook5/Source/web/Areas/Management/ViewModels/PlayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using web.ApiInfrastructure.Client;
using web.Areas.Management.Models.TeamManagement;

namespace web.Areas.Management.ViewModels
{
    public class PlayViewModel
    {
        public PlayViewModel()
        {
            Plays = new List<Play>();
            Playbooks = new List<PlayBook>();
            TeamInstall = new TeamInstall();
            TeamNotes = new TeamNoteList();
            TeamUsers = new List<TeamUser>();
        }

        public async Task Load(string teamId)
        {
            if (!string.IsNullOrEmpty(teamId))
            {
                Plays = await GetAllPlaysByTeamId(teamId);
                Playbooks = await GetAllPlaybooksByTeamId(teamId);
                TeamInstall = await GetAllTeamInstalledByTeamId(teamId);
                TeamNotes = await GetAllTeamNotesByTeamId(teamId);
                TeamUsers = await GetUsersByTeamId(teamId);
                TeamId = teamId;
            }
        }

        public string TeamId { get; set; }
        public List<Play> Plays { get; set; }
        public List<PlayBook> Playbooks { get; set; }
        public TeamInstall TeamInstall { get; set; }
        public TeamNoteList TeamNotes { get; set; }
        public List<TeamUser> TeamUsers { get; set; }
        

        public async Task<List<Play>> GetAllPlaysByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<Play>>($"api/PlaybookManagement/GetAllPlaysByTeamId?teamid={teamId}");
        }

        public async Task<TeamNoteList> GetAllTeamNotesByTeamId(string teamId)
        {
            return await new RestHelper().Get<TeamNoteList>($"api/TeamNotes/GetAllTeamNotesByTeamId?teamid={teamId}");
        }

        public async Task<List<PlayBook>> GetAllPlaybooksByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<PlayBook>>($"api/PlaybookManagement/GetAllPlaybooksByTeamId?teamid={teamId}");
        }

        public async Task<TeamInstall> GetAllTeamInstalledByTeamId(string teamId)
        {
            return await new RestHelper().Get<TeamInstall>($"api/TeamManagement/TeamInstallsByIdGet/{teamId}");
        }
        
        public async Task<bool> CreateUpdateTestInstall(TeamInstallDTO teamInstall)
        {
            return await new RestHelper().Post("api/TeamManagement/CreateTeamInstall", teamInstall);
        }

        public async Task<bool> InsertInstallPlay(string teamId, string playId)
        {
            return await new RestHelper().Get($"api/TeamManagement/InsertInstallPlay?id={teamId}&playId={playId}");
        }


        public async Task<bool> DeleteTeamNotesById(string id)
        {
            return await new RestHelper().Get($"api/TeamNotes/DeleteTeamNotesById?id={id}");
        }

        public async Task<bool> DeletePlayById(string id)
        {
            return await new RestHelper().Get($"api/PlaybookManagement/DeletePlayById?id={id}");
        }
        public async Task<bool> DeleteInstallPlay(string id, string playId)
        {
            return await new RestHelper().Get($"api/TeamManagement/DeleteInstallPlay?id={id}&playId={playId}");
        }

        public async Task<bool> SavePlay(Play play)
        {
            return await new RestHelper().Post($"api/PlaybookManagement/CreatePlay", play);
        }

        public async Task<bool> CreateTeamNotes(TeamNote teamNote)
        {
            return await new RestHelper().Post($"api/TeamNotes/CreateTeamNotes", teamNote);
        }

        public async Task<string> UploadPreview(string teamName, string playId, string fileName, byte[] fileBytes, int contentLength, string parameterName, string contentType)
        {
            return await new RestHelper().Upload($"api/PlaybookManagement/UploadPreviewFiles?teamName={teamName}&playId={playId}", fileName, fileBytes, contentLength, parameterName, contentType);
        }

        public async Task<string> UploadFile(string teamName, string playId, string fileName, byte[] fileBytes, int contentLength, string parameterName, string contentType)
        {
            return await new RestHelper().Upload($"api/PlaybookManagement/UploadFiles?teamName={teamName}&playId={playId}", fileName, fileBytes, contentLength, parameterName, contentType);
        }

        public async Task<List<TeamUser>> GetUsersByTeamId(string teamId)
        {
            return await new RestHelper().Get<List<TeamUser>>($"api/TeamManagement/GetAllUsersByTeamId?teamid={teamId}");
        }
    }
}

Playbook5/Source/web/Areas/Management/Controllers/PlaysController.cs
using Newtonsoft.Json;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using web.Areas.Management.Models.TeamManagement;
using web.Areas.Management.ViewModels;

namespace web.Areas.Management.Controllers
{
    public class PlaysController : Controller
    {
        // GET: Management/Plays
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Library(string teamId)
        {
            PlayViewModel model = new PlayViewModel();
            await model.Load(teamId);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> SavePlay(string teamId, Models.TeamManagement.Play play)
        {
            var viewModel = new TeamViewModel();
            play.TeamId = teamId;
            await viewModel.Load(teamId);
            if (Request.Form["PlaybookType"] == "Offense")
            {
                if (viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]) != null)
                {
                    play.PlaybookId = viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]).Id;
                }
                else
                {
                    PlayBook newPlaybook = new PlayBook();
                    newPlaybook.TeamId = teamId;
                    newPlaybook.PlaybookType = new PlaybookTypes { Name = "Offense", FriendlyName = "Offense" };
                    var playBookResult = await viewModel.CreateUpdateTeamPlayBook(newPlaybook);
                    play.PlaybookId = playBookResult.Id;

                }

            }
            else if (Request.Form["PlaybookType"] == "Defense")
            {
                if (viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]) != null)
                {
                    play.PlaybookId = viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]).Id;
                }
                else
                {
                    PlayBook newPlaybook = new PlayBook();
                    newPlaybook.TeamId = teamId;
                    newPlaybook.PlaybookType = new PlaybookTypes { Name = "Defense", FriendlyName = "Defense" };
                    var playResult = await viewModel.CreateUpdateTeamPlayBook(newPlaybook);
                    play.PlaybookId = playResult.Id;
                }

            }
            else if (Request.Form["PlaybookType"] == "Special Team")
            {
                if(viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]) != null)
                {
                    play.PlaybookId = viewModel.Team.Playbooks.FirstOrDefault(x => x.PlaybookType.Name == Request.Form["PlaybookType"] || x.PlaybookType.FriendlyName == Request.Form["PlaybookType"]).Id;
                }
                else
                {
                    PlayBook newPlaybook = new PlayBook();
                    newPlaybook.TeamId = teamId;
                    newPlaybook.PlaybookType = new PlaybookTypes { Name = "Special Team", FriendlyName = "Special Team" };
                    var playResult = await viewModel.CreateUpdateTeamPlayBook(newPlaybook);
                    play.PlaybookId = playResult.Id;
                }
                
            }

            play.RecommendedPlays = Request.Form["RecommendedPlaysHidden"].Split(',').Where(x => !string.IsNullOrEmpty(x)).Select(x => new RecommendedPlay { PlayId = x }).ToList();

            play.TeamName = viewModel.Team.Name;

            play.OffenseFormation.Name = play.OffenseFormation.FriendlyDisplay;

            play.DefenseFormation = new Models.TeamManagement.DefenseFormation();
            play.DefenseFormation.Name = "Defense";
            play.DefenseFormation.FriendlyDisplay = "Defense";
            play.DefenseFormation.Id = 1;

            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    if (Request.Files.AllKeys.Contains("filepreview"))
                    {
                        var file = Request.Files["filepreview"];
                        MemoryStream target = new MemoryStream();
                        file.InputStream.CopyTo(target);
                        byte[] data = target.ToArray();
                        if (data.Length > 0)
                            play.PreviewUrl = await viewModel.UploadPreview(viewModel.Team.Name, "0", file.FileName, data, file.ContentLength, "UploadPreviewFiles", file.ContentType);
                    }

                    if (Request.Files.AllKeys.Contains("file"))
                    {
                        var file = Request.Files["file"];
                        MemoryStream target = new MemoryStream();
                        file.InputStream.CopyTo(target);
                        byte[] data = target.ToArray();
                        if (data.Length > 0)
                            play.SvgUrl = await viewModel.UploadPreview(viewModel.Team.Name, "0", file.FileName, data, file.ContentLength, "uploadedFile", file.ContentType);
                    }
                }

                if (await viewModel.SavePlay(play))
                {
                    TempData["ErrorMessage"] = "New play has been added to team";
                }
                else
                {
                    TempData["ErrorMessage"] = "There is some problem in adding play to team";
                }
            }
            else
            {
                TempData["ErrorMessage"] = "Please review fields";
            }
            ActionResult result;
            result = RedirectToAction("Library", new { teamId = teamId });
            return await Task.FromResult(result);
        }
        [HttpGet]
        public async Task<ActionResult> DeletePlayById(string id, string teamId)
        {
            var viewModel = new TeamViewModel();
            if (await viewModel.DeletePlayById(id))
            {
                TempData["ErrorMessage"] = "Play is deleted from install";
            }
            else
            {
                TempData["ErrorMessage"] = "There is some problem in deleting play";
            }

            ActionResult result;
            result = RedirectToAction("Library", new { teamId = teamId });
            return await Task.FromResult(result);
        }

        [HttpGet]
        public async Task<ActionResult> GetPlayDetail(string teamId, string playId, string playbookType)
        {
            try
            {
                var viewModel = new TeamViewModel();
                await viewModel.Load(teamId);
                var play = viewModel.Team.Plays.FirstOrDefault(x => x.Id == playId);
                play.RecommendedPlayList = JsonConvert.SerializeObject(play.RecommendedPlays);
                ViewData["TeamId"] = teamId;
                ViewData["PlaybookType"] = playbookType;
                if (playbookType == "Offense")
                {
                    var defensePlaybooks = viewModel.Team.Playbooks.Where(x => x.PlaybookType.Name == "Defense" || x.PlaybookType.FriendlyName == "Defense").Select(x => x.Id).ToList();
                    ViewData["RecommendedPlays"] = viewModel.Team.Plays.Where(x => defensePlaybooks.Contains(x.PlaybookId)).ToList();
                }
                else if (playbookType == "Defense")
                {
                    var offensePlaybooks = viewModel.Team.Playbooks.Where(x => x.PlaybookType.Name == "Offense" || x.PlaybookType.FriendlyName == "Offense").Select(x => x.Id).ToList();
                    ViewData["RecommendedPlays"] = viewModel.Team.Plays.Where(x => offensePlaybooks.Contains(x.PlaybookId)).ToList();
                }
                else if (playbookType == "Special Team")
                {
                    var specialPlaybooks = viewModel.Team.Playbooks.Where(x => x.PlaybookType.Name == "Special Team" || x.PlaybookType.FriendlyName == "Special Team").Select(x => x.Id).ToList();
                    ViewData["RecommendedPlays"] = viewModel.Team.Plays.Where(x => specialPlaybooks.Contains(x.PlaybookId)).ToList();
                }
                else
                {
                    ViewData["RecommendedPlays"] = viewModel.Team.Plays.ToList();
                }
                return PartialView("_AddPlayForm", play);
            }
            catch (Exception ex)
            {
                return null;
            }
        }
    }
}

Playbook5/Source/web/Areas/Management/Views/Plays/Library.cshtml
@using web.Areas.Management.Models.TeamManagement
@using web.Areas.Management.ViewModels
@model PlayViewModel
@{
    ViewBag.Title = "TeamDetails";
    Layout = "~/Areas/Management/Views/Shared/_Layout.cshtml";
}

<div class="main-section" id="Top">
    <div class="container container_upperbuttons w-container">
        <ul class="nav nav-tabs">
            <li><a class="button_upper button_upperleft gray-button w-button" href="javascript:void" onclick="window.history.go(-1)">BACK</a></li>
            <li>
                <a class="button_upper button_upperleft gray-button w-button" href="~/Management/TeamManagement/TeamDetails/@Model.TeamId">TEAM</a>
            </li>
            <li class="active"><a class="button_upper button_upperleft gray-button w-button" href="@Url.Action("Library", "Plays", new { teamId = Model.TeamId})">PLAYS</a></li>
            <li><a class="button_upper button_upperleft gray-button w-button" href="@Url.Action("Install", "Install", new { teamId = Model.TeamId})">INSTALL</a></li>
            <li><a class="button_upper button_upperleft gray-button w-button" href="#">REPORTING</a></li>
        </ul>
    </div>
</div>
@{
    var offensePlaybooks = Model.Playbooks.Where(x => x.PlaybookType.Name == "Offense" || x.PlaybookType.FriendlyName == "Offense").Select(x => x.Id).ToList();
    var offensePlays = Model.Plays.Where(x => offensePlaybooks.Contains(x.PlaybookId) && x.Active != false).ToList();

    var defensePlaybooks = Model.Playbooks.Where(x => x.PlaybookType.Name == "Defense" || x.PlaybookType.FriendlyName == "Defense").Select(x => x.Id).ToList();
    var defensePlays = Model.Plays.Where(x => defensePlaybooks.Contains(x.PlaybookId) && x.Active != false).ToList();

    var specialPlaybooks = Model.Playbooks.Where(x => x.PlaybookType.Name == "Special Team" || x.PlaybookType.FriendlyName == "Special Team").Select(x => x.Id).ToList();
    var specialPlays = Model.Plays.Where(x => specialPlaybooks.Contains(x.PlaybookId) && x.Active != false).ToList();

    var archivedPlays = Model.Plays.Where(x => x.Active == false).ToList();
}
<div class="clearfix">
    <div class="col-md-offset-2 col-md-8 text-center">
        <div class="fullview-wrapper clearfix">
            @{
                if (TempData["ErrorMessage"] != null)
                {
                    <div class="row btn-danger">
                        @Html.Label(TempData["ErrorMessage"] as string)
                    </div>
                    TempData["ErrorMessage"] = null;
                }
            }

            <div class="col-md-3">
                <h4 class="text-uppercase">Offense</h4>
                @*<div class="">@(Model.Plays != null ? Model.Plays.Count.ToString() : "")</div>*@
                <div class="">@offensePlays.Count</div>
            </div>
            <div class="col-md-3">
                <h4 class="text-uppercase">Defense</h4>
                <div class="">@defensePlays.Count</div>
            </div>
            <div class="col-md-3">
                <h4 class="text-uppercase">Special Teams</h4>
                <div class="">@specialPlays.Count</div>
            </div>
            <div class="col-md-3">
                <h4 class="text-uppercase">Total Plays</h4>
                <div class="">@(offensePlays.Count + defensePlays.Count + specialPlays.Count )</div>
            </div>
        </div>
    </div>
</div>
<div class="offset-top">
    <div id="LibraryTabk">
        <div class="w-container tab-content">
            <ul class="nav nav-tabs playes-tab">
                <li class="active"><a data-toggle="tab" href="#LibraryOffense">Offense</a></li>
                <li><a data-toggle="tab" href="#LibraryDefense">Defense</a></li>
                <li><a data-toggle="tab" href="#LibrarySpecialTeams">Special Teams</a></li>
                <li class="archived"><a data-toggle="tab" href="#LibraryArchive" class="disabled">Archived</a></li>
            </ul>
            @Html.Partial("_LibraryTabContent", offensePlays, new ViewDataDictionary { { "TeamId", Model.TeamId } })
            @Html.Partial("_LibraryDefenseContent", defensePlays, new ViewDataDictionary { { "TeamId", Model.TeamId } })
            @Html.Partial("_LibrarySpecialTeamContent", specialPlays, new ViewDataDictionary { { "TeamId", Model.TeamId } })
            @Html.Partial("_LibraryArchiveContent", archivedPlays, new ViewDataDictionary { { "TeamId", Model.TeamId } })
        </div>
    </div>
</div>

@Html.Partial("_AddPlayForm", new Play(), new ViewDataDictionary { { "TeamId", Model.TeamId }, { "PlaybookType", "Offense" }, { "RecommendedPlays", defensePlays } })
@Html.Partial("_AddPlayForm", new Play(), new ViewDataDictionary { { "TeamId", Model.TeamId }, { "PlaybookType", "Defense" }, { "RecommendedPlays", offensePlays } })
@Html.Partial("_AddPlayForm", new Play(), new ViewDataDictionary { { "TeamId", Model.TeamId }, { "PlaybookType", "Special Team" }, { "RecommendedPlays", specialPlays } })